name: Build Python Project with PyInstaller

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.9]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Clone ScriptBlocks repository
      run: |
        git clone https://github.com/ScriptBlocks/ScriptBlocks.py.git
        cd ScriptBlocks.py
        python setup.py install

    - name: Install additional dependencies
      run: |
        pip install -r requirements.txt

    - name: Build executable
      run: |
        if [[ $RUNNER_OS == 'Windows' ]]; then
          pyinstaller --onefile --noconsole your_script.py
        else
          pyinstaller --onefile your_script.py
        fi

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: built-executable
        path: dist/